GET http://localhost:3001/api/pairings
Content-Type: application/json

{
    "userId": 1
}


###
POST http://localhost:3001/api/pairings
Content-Type: application/json

{
    "tuteeId": 2,
    "tutorId": 3,
    "userId": 1,
    "location": "Punggol",
    "strengths": "Ah Lian is an enthusiastic girl.",
    "weaknesses": "Ah Lian is sometimes distracted during lessons.",
    "goals": "I hope that Ah Lian can get 100% for her Bio test next week."
}