GET http://localhost:3001/api/pairings/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwiaWQiOjEsImlhdCI6MTY5NjQzMDE2OH0.AbPBzbddifF6Oj8-dtLGMzKTH3BcnIHY0JGbTCuLlmM


###
POST http://localhost:3001/api/pairings
Content-Type: application/json

{
    "tuteeId": 2,
    "tutorId": 3,
    "userId": 1,
    "location": "Punggol",
    "strengths": "Ah Lian is an enthusiastic girl.",
    "weaknesses": "Ah Lian is sometimes distracted during lessons.",
    "goals": "I hope that Ah Lian can get 100% for her Bio test next week."
} 