GET http://localhost:3001/api/sessions


###
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
    "pairingId": "6",
    "date": "2023-09-27",
    "hours": 2,
    "overview": "Meng Peh's PSLE Math paper is just 2 days away. He has worked very hard for it and I am sure he will do well.",
    "problems": "None.",
    "nextSession": "This is my last lesson with him. I wish him all the best for his paper!"
}