GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Search Token",
    "name": "searchtoken",
    "password": "hotbond1621secrettoken",
    "email": "searchtoken@gmail.com",
    "organisation": "EduHopeSG"
}

###
PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
    "password": "eduhopesg"
}